{
 "title": "Grafana Analytics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Note, this dashboard is not monitored by macropower-analytics-panel.\n\nTo generate some activity, head over to: [Analytics Panel Example Dashboard](/d/ZQZXRMXMk/analytics-panel-example-dashboard?orgId=1)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sessions by Dashboard",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum by (dashboard_name) (increase(grafana_analytics_sessions_total[$__rate_interval])))",
     "legendFormat": "{{ dashboard_name }}"
    }
   ]
  },
  {
   "title": "Session Duration by Dashboard",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (dashboard_name) (increase(grafana_analytics_sessions_duration_seconds_total[$__rate_interval]))",
     "legendFormat": "{{ dashboard_name }}"
    }
   ]
  },
  {
   "title": "Sessions by Username",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum by (user_name) (increase(grafana_analytics_sessions_total[$__rate_interval])))",
     "legendFormat": "{{ user_name}}"
    }
   ]
  },
  {
   "title": "Session Duration by Username",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (user_name) (increase(grafana_analytics_sessions_duration_seconds_total[$__rate_interval]))",
     "legendFormat": "{{ user_name}}"
    }
   ]
  }
 ]
}